### ISSUE TITLE
No need to use serial port to display text

### ISSUE THREAD

**Issue by xcaptain** [Freax13/test-kernel#4]
https://github.com/Freax13/test-kernel/blob/1013121f1d9d619248ed609e48cf0d47d5a04e6e/src/logger.rs#L26-L28

I found these lines have no effect, if I remove them, the log will still appear. I think framebuffer is the recommended way to display text and [a wiki](https://en.wikipedia.org/wiki/COM_(hardware_interface)) says COM has been removed from modern computers. Do you think it's ok to remove these lines?

**Comment by Freax13** [comment]
Nope, they have an effect on computers with serial ports. While they are less common nowadays, there actually still exist modern computers that have serial ports (e.g. I own an 11th gen Intel NUC that has a serial port). A serial port can also be enabled in qemu by adding `-serial stdio` to the command line arguments.

**Comment by xcaptain** [comment]
Thanks, I added `-serial stdio` and see the log on my host machine not in the guest machine, maybe in a real machine log can be displayed through serial port.
